### ISSUE TITLE
Add Crystals

### ISSUE THREAD

**Issue by adrwa** [MinecraftModDevelopment/FantasyMetals#3]
Ideas for a few of these crystals
the specific uses of these crystals are **[REDACTED]**
i put ore dictionary values in the brackets
- Gali Crystal (crystalGali) 10 10 10
- Ska Crystal (crystalSka) 10 10 10
- Ender Crystal (crystalEnd) 10 10 10
- Hell Crystal (crystalHell) 10 10 10
- Ovr Crystal (crystalOvr) 10 10  10
- Sez Crystal (crystalSez) 10 10 10
- Mea Crystal (crystalMea) 10 10 10
- Abydos Crystal (crystalAbydos) 10 10 10
- Agora Crystal (crystalAgora) 10 10 10
- Kahler Crystal (crystalKahler ) 10 10 10
- Leophantos Crystal (crystalLeophantos) 10 10 10
- Oblivion Crystal (crystalOblivion ) 10 10 10
- Raaga Crystal (crystalRaaga) 10 10 10
- N-Space Crystal (crystalNSpace) 10 10 10
- Rift Crystal (crystalRift) 10 10 10
- Lotus Crystal (crystalLotus) 10 10 10
- Xenon Crystal (crystalXenon) 10 10 10

Might be more listed later.

**Comment by jriwanek** [comment]
You'll need to provide block stats in the format used in:
https://github.com/jriwanek/FantasyMetals/blob/master/src/main/java/fantasymetals/init/Materials.java

Also, will you be providing art?
